FROM node:20

WORKDIR /usr/src/app

COPY package*.json ./
RUN npm install

# Install Angular CLI globally
RUN npm install -g @angular/cli

COPY . .

EXPOSE 4200

CMD ["ng", "serve", "--host", "0.0.0.0", "--poll", "2000"]